/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 * LM
 */
declare namespace El {
  export type ementaryDOM = Element | Element[];
  export type Element = string | number | null | boolean | HTMLElement | HTMLStyleElement | HTMLComment;

  /**
   * HTMLElements have a single property: a tagname, with a value of an array of childNodes | an object of HTML attributes
   */
  export interface HTMLElement {
    /**
     * This interface was referenced by `ELHTMLElement`'s JSON-Schema definition
     * via the `patternProperty` "^[A-Za-z]+[A-Za-z0-9_]*".
     */
    [k: string]:
      | Element[]
      | {
          style?: CSSStyleDeclaration;
          childNodes?: Element[];
          [k: string]: unknown;
        };
  }
  /**
   * CSS properties and their values
   *
   * This interface was referenced by `ELCSSStyleSheet`'s JSON-Schema definition
   * via the `patternProperty` "^@(font-face|page)".
   */
  export interface CSSStyleDeclaration {
    [k: string]: string;
  }
  export interface HTMLStyleElement {
    style: CSSStyleSheet;
    [k: string]: unknown;
  }
  export interface CSSStyleSheet {
    [k: string]: unknown;
  }
  export interface HTMLComment {
    "!": string;
    [k: string]: unknown;
  }
}