/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type ElementaryDOM = ELElement | ELElement[];
export type ELElement = string | number | null | boolean | ELHTMLElement | ELHTMLStyleElement | ELHTMLComment;

/**
 * HTMLElements have a single property: a tagname, with a value of an array of childNodes | an object of HTML attributes
 */
export interface ELHTMLElement {
  /**
   * This interface was referenced by `ELHTMLElement`'s JSON-Schema definition
   * via the `patternProperty` "^[A-Za-z]+[A-Za-z0-9_]*".
   */
  [k: string]:
    | ELElement[]
    | {
        style?: ELCSSStyleDeclaration;
        childNodes?: ELElement[];
        [k: string]: unknown;
      };
}
/**
 * CSS properties and their values
 *
 * This interface was referenced by `ELCSSStyleSheet`'s JSON-Schema definition
 * via the `patternProperty` "^@(font-face|page)".
 */
export interface ELCSSStyleDeclaration {
  [k: string]: string;
}
export interface ELHTMLStyleElement {
  style: ELCSSStyleSheet;
  [k: string]: unknown;
}
export interface ELCSSStyleSheet {
  [k: string]: unknown;
}
export interface ELHTMLComment {
  "!": string;
  [k: string]: unknown;
}
